Feature/global renaming to patternatlas
PatternAtlas/pattern-atlas-api pull request #27
Opened 2021-06-21 07:50 UTC by manuwei

* rename all occurence of the old PatternPedia name to PatternAtlas
* rename group name to follow naming conventions of the Quantil orga (resolves [issue-description](https://github.com/orgs/UST-QuAntiL/projects/2#card-63295966)) 
* change version

2021-06-21 10:57 UTC, lharzenetter requested changes

2021-06-21 10:57 UTC, lharzenetter commented on intellij-idea-code-style.xml
> +            <package name="io.github.ust.quantil.patternatlas.api" withSubpackages="true" static="false"/>
Wouldn't this be `io.github.patternatlas.api`? (as https://patternatlas.github.io/pattern-atlas-api/)

2021-06-21 10:57 UTC, lharzenetter commented on pom.xml
> +    <groupId>io.github.ust.quantil.patternatlas</groupId>
See above

2021-06-21 14:21 UTC, lharzenetter requested changes

2021-06-21 14:21 UTC, lharzenetter commented on intellij-idea-code-style.xml
> +            <package name="io.github.ust.quantil.patternatlas.api" withSubpackages="true" static="false"/>
Somehow this didn't get updated...

2021-06-21 14:21 UTC, lharzenetter commented on src/main/java/io/github/patternatlas/api/entities/candidate/Candidate.java
> +    //    @Type(type = "jsonb")
Maybe delete these commented lines?

2021-06-21 14:21 UTC, lharzenetter commented on src/main/java/io/github/patternatlas/api/entities/user/UserEntity.java
>  //    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, orphanRemoval = true)
Maybe delete these commented lines?

2021-06-22 09:02 UTC, manuwei commented
I fix the last instance where the package name need to be corrected. I am aware of that there is too much commented code for the pattern candidates/usermangement feature - but I think that's a separate bug/feature to be considered, so I added an [issue](https://github.com/PatternAtlas/pattern-atlas-api/issues/28) for it.

2021-06-22 09:16 UTC, lharzenetter approved these changes

2021-06-22 10:53 UTC, merged